controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_position_controller:
      type: forward_command_controller/ForwardCommandController


forward_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2-dm
      - joint2-mu
      - joint3-dm
      - joint3-mu
      - joint4-dm
      - joint4-mu
      - joint5-dm
      - joint5-mu
    
    interface_name: position


  